plugins {
    id 'com.android.application'
}

android {
    namespace 'com.disdikbudbatang.simantab'
    compileSdk 35

    defaultConfig {
        applicationId 'com.disdikbudbatang.simantab'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    signingConfigs {
        release {
            storeFile file('simantab-upload-key.jks')
            storePassword System.getenv('SIMANTAB_KEYSTORE_PASSWORD') ?: ''
            keyAlias System.getenv('SIMANTAB_KEY_ALIAS') ?: 'simantab'
            keyPassword System.getenv('SIMANTAB_KEY_PASSWORD') ?: ''
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
