import fs from 'node:fs/promises';
import { spawnSync } from 'node:child_process';

const SOURCE='https://simantab-online.vercel.app/';
const PATCHES=[
 {file:'kp-enhancement.js',url:'https://raw.githubusercontent.com/ariefupgriss3-eng/Simantab-online/main/web/kp-enhancement.js',marker:'SIMANTAB_KP_SOP_UI_V1',version:4},
 {file:'ptk-swasta-enhancement.js',url:'https://raw.githubusercontent.com/ariefupgriss3-eng/Simantab-online/main/web/ptk-swasta-enhancement.js',marker:'SIMANTAB_PTK_SWASTA_UI_V1',version:1},
 {file:'super-admin-enhancement.js',url:'https://raw.githubusercontent.com/ariefupgriss3-eng/Simantab-online/main/web/super-admin-enhancement.js',marker:'SIMANTAB_SUPER_ADMIN_COMMAND_CENTER_V1',version:3},
 {file:'kadin-dashboard-v2.js',url:'https://raw.githubusercontent.com/ariefupgriss3-eng/Simantab-online/main/web/kadin-dashboard-v2.js',marker:'SIMANTAB_KEPALA_DINAS_INFOGRAPHIC_V2',version:3},
 {file:'dinas-login-enhancement.js',url:'https://raw.githubusercontent.com/ariefupgriss3-eng/Simantab-online/main/web/dinas-login-enhancement.js',marker:'SIMANTAB_DINAS_USERNAME_LOGIN_V1',version:1}
];
const FILE_LIMIT=512000;
async function getText(url,fallback=''){try{const r=await fetch(url,{headers:{'user-agent':'SIMANTAB-Vercel-Build/2.3'},cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return await r.text()}catch(e){console.error('fetch text failed',url,e.message);return fallback}}
async function getBinary(url){try{const r=await fetch(url,{headers:{'user-agent':'SIMANTAB-Vercel-Build/2.3'},cache:'no-store'});if(!r.ok)return null;return Buffer.from(await r.arrayBuffer())}catch{return null}}
async function syntax(name,code){const path=`/tmp/${name}.mjs`;await fs.writeFile(path,code);const r=spawnSync(process.execPath,['--check',path],{encoding:'utf8'});if(r.status!==0)throw new Error(`Syntax check ${name} gagal: ${(r.stderr||r.stdout||'').trim()}`)}
function removeExternal(html,file){const safe=file.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return html.replace(new RegExp(`<script\\s+type=["']module["']\\s+src=["']\\./${safe}(?:\\?v=\\d+)?["']><\\/script>\\s*`,'gi'),'')}
function removeInlineMarker(html,marker){for(let guard=0;guard<4&&html.includes(marker);guard++){const pos=html.indexOf(marker),start=html.lastIndexOf('<script type="module">',pos),end=html.indexOf('</script>',pos);if(start<0||end<0)break;html=html.slice(0,start)+html.slice(end+9)}return html}
let html=await getText(SOURCE);if(!html||!html.includes('SIMANTAB Online'))throw new Error('Gagal mengambil frontend SIMANTAB produksi.');
const modules={};for(const p of PATCHES){const code=await getText(p.url);if(!code||!code.includes(p.marker))throw new Error(`Patch ${p.file} tidak tersedia.`);modules[p.file]=code;html=removeInlineMarker(html,p.marker);html=removeExternal(html,p.file)}
html=removeExternal(html,'kadin-dashboard-enhancement.js');
html=html.replaceAll('maksimal 1 MB per berkas','maksimal 500 KB per berkas').replaceAll('maksimal 1 MB per file','maksimal 500 KB per file').replaceAll('batas 1 MB','batas 500 KB').replaceAll('f.size<=1048576',`f.size<=${FILE_LIMIT}`).replaceAll('f.size>1048576',`f.size>${FILE_LIMIT}`);
const ROLE_LABEL="const ROLE_LABEL={SUPER_ADMIN:'Super Admin SIMANTAB',KEPALA_DINAS:'Kepala Disdikbud',KABID:'Kabid Ketenagaan',KASI_SD:'Kasi PPTK SD',KASI_SMP:'Kasi PPTK SMP',SUBKOOR_TK:'Subkoor PPTK TK/PAUD',STAFF_DINAS:'Staf Dinas',STAFF_TPG:'Staff TPG/Tamsil',PENGAWAS:'Pengawas',KEPALA_SEKOLAH:'Kepala Sekolah',GTK:'GTK'};";
const DINAS_ROLES="const DINAS_ROLES=['SUPER_ADMIN','KEPALA_DINAS','KABID','KASI_SD','KASI_SMP','SUBKOOR_TK','STAFF_DINAS','STAFF_TPG','PENGAWAS'];";
if(!/const ROLE_LABEL=\{[^;]+\};/.test(html)||!/const DINAS_ROLES=\[[^;]+\];/.test(html))throw new Error('Anchor role tidak ditemukan.');html=html.replace(/const ROLE_LABEL=\{[^;]+\};/,ROLE_LABEL).replace(/const DINAS_ROLES=\[[^;]+\];/,DINAS_ROLES);
const sbNeedle='const sb = createClient(SUPABASE_URL, SUPABASE_KEY);';if(!html.includes(sbNeedle))throw new Error('Anchor Supabase client tidak ditemukan.');if(!html.includes('window.__simantabSb=sb;'))html=html.replace(sbNeedle,sbNeedle+'\nwindow.__simantabSb=sb;');
const profileNeedle='profile=await ensureProfile();';if(!html.includes(profileNeedle))throw new Error('Anchor profil login tidak ditemukan.');if(!html.includes('profile=await ensureProfile();window.__simantabProfile=profile;'))html=html.replace(profileNeedle,profileNeedle+'window.__simantabProfile=profile;');
const saveProfileNeedle='profile=data;';if(html.includes(saveProfileNeedle)&&!html.includes('profile=data;window.__simantabProfile=profile;'))html=html.replace(saveProfileNeedle,saveProfileNeedle+'window.__simantabProfile=profile;');
const bodyClose=html.lastIndexOf('</body>');if(bodyClose<0)throw new Error('Tag penutup body tidak ditemukan.');const tags=PATCHES.map(p=>`<script type="module" src="./${p.file}?v=${p.version}"></script>`).join('\n')+'\n';html=html.slice(0,bodyClose)+tags+html.slice(bodyClose);
const mainOpen='<script type="module">',mainStart=html.indexOf(mainOpen),mainEnd=html.indexOf('</script>',mainStart+mainOpen.length);if(mainStart<0||mainEnd<0)throw new Error('Script utama tidak ditemukan.');const mainJs=html.slice(mainStart+mainOpen.length,mainEnd);await syntax('simantab-main',mainJs);for(const p of PATCHES){await syntax(p.file.replace('.js',''),modules[p.file]);if(html.lastIndexOf(`${p.file}?v=${p.version}`)<=mainEnd)throw new Error(`Modul ${p.file} tidak berada di luar script utama.`)}
if(!mainJs.includes("KEPALA_DINAS:'Kepala Disdikbud'")||!mainJs.includes("STAFF_DINAS:'Staf Dinas'")||!mainJs.includes("'SUPER_ADMIN','KEPALA_DINAS','KABID'"))throw new Error('Hierarki role Dinas belum terpasang.');
if(!modules['kadin-dashboard-v2.js'].includes("DASH_ROLES=['SUPER_ADMIN','KEPALA_DINAS','KABID','KASI_SD','KASI_SMP','SUBKOOR_TK']"))throw new Error('Cakupan dashboard pimpinan berjenjang belum terpasang.');
if(!modules['dinas-login-enhancement.js'].includes('SIMANTAB_DINAS_USERNAME_LOGIN_V1')||!modules['dinas-login-enhancement.js'].includes('simantab-username-login')||!modules['dinas-login-enhancement.js'].includes('simantab-account-settings'))throw new Error('Login username Dinas belum terpasang.');
await fs.mkdir('.vercel/output/static',{recursive:true});await fs.writeFile('.vercel/output/config.json',JSON.stringify({version:3}));await fs.writeFile('.vercel/output/static/index.html',html);for(const p of PATCHES)await fs.writeFile(`.vercel/output/static/${p.file}`,modules[p.file]);const manifest=await getText(SOURCE+'manifest.json',JSON.stringify({name:'SIMANTAB Online',short_name:'SIMANTAB',start_url:'/',display:'standalone',theme_color:'#0f3f76',background_color:'#f4f7fb'}));await fs.writeFile('.vercel/output/static/manifest.json',manifest);const sw=`const CACHE_VERSION='simantab-v18';self.addEventListener('install',()=>self.skipWaiting());self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.map(k=>caches.delete(k)))).then(()=>self.clients.claim())));self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;e.respondWith(fetch(e.request,{cache:'no-store'}).catch(()=>caches.match(e.request)))})`;await fs.writeFile('.vercel/output/static/sw.js',sw);for(const f of ['icon-192.png','icon-512.png']){const b=await getBinary(SOURCE+f);if(b)await fs.writeFile('.vercel/output/static/'+f,b)}console.log(JSON.stringify({ok:true,roleOrder:'SUPER_ADMIN > KEPALA_DINAS > KABID > KASI/SUBKOOR > STAFF',dashboardRoles:['SUPER_ADMIN','KEPALA_DINAS','KABID','KASI_SD','KASI_SMP','SUBKOOR_TK'],scoped:{KASI_SD:'SD',KASI_SMP:'SMP',SUBKOOR_TK:'TK'},dinasUsernameLogin:true,firstLoginPasswordChange:true,uploadLimitBytes:FILE_LIMIT}));
