/* SIMANTAB_DIKLAT_KS_BCKS_V1 */
(async()=>{
const wait=ms=>new Promise(r=>setTimeout(r,ms));
for(let i=0;i<200&&(!window.__simantabSb||!window.showTab||!window.__simantabProfile);i++)await wait(50);
const sb=window.__simantabSb,$=id=>document.getElementById(id),profile=()=>window.__simantabProfile||{};
if(!sb||!window.showTab)return;
const FILE_LIMIT=512000;
const BUCKET='simantab-documents';
const REQUIREMENTS=[
 ['IJAZAH_TERAKHIR','Ijazah terakhir'],['SERTIFIKAT_PENDIDIK','Sertifikat Pendidik'],['SK_PNS','SK PNS'],['SKP_1','SKP 1'],['SKP_2','SKP 2'],['SK_PENGALAMAN_MANAJERIAL','SK pengalaman Manajerial'],['SK_HUDIS','SK Hudis'],['SKCK','SKCK'],['PAKTA_INTEGRITAS','Pakta Integritas']
];
const REVIEW_ROLES=new Set(['SUPER_ADMIN','KEPALA_DINAS','SEKRETARIS_DINAS','KABID','KASI_SD','KASI_SMP','SUBKOOR_TK']);
const isReviewer=()=>REVIEW_ROLES.has(profile().role);
const isApplicant=()=>['GTK','KEPALA_SEKOLAH'].includes(profile().role);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtDate=v=>v?new Date(v).toLocaleDateString('id-ID'):'-';
const fmtDateTime=v=>v?new Date(v).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'}):'-';
const toast=(msg,bad=false)=>{let t=document.getElementById('ksBcksToast');if(!t){t=document.createElement('div');t.id='ksBcksToast';Object.assign(t.style,{position:'fixed',right:'18px',bottom:'22px',zIndex:99999,maxWidth:'360px',padding:'12px 16px',borderRadius:'12px',boxShadow:'0 8px 28px #0003',fontWeight:'700'});document.body.appendChild(t)}t.style.background=bad?'#fee2e2':'#dcfce7';t.style.color=bad?'#991b1b':'#166534';t.textContent=msg;clearTimeout(t._x);t._x=setTimeout(()=>t.remove(),3500)};
function mainEl(){return document.querySelector('main.content')}
function ensureSection(){if($('diklatKsBcks'))return;const main=mainEl();if(!main)return;const sec=document.createElement('section');sec.id='diklatKsBcks';sec.className='section';sec.innerHTML='<div class="head"><div><h2>Diklat KS/BCKS</h2><p>Workflow seleksi administrasi, seleksi substansi, Diklat, dan penerbitan sertifikat.</p></div></div><div id="diklatKsBcksBody"></div>';const footer=main.querySelector('.footer');if(footer)main.insertBefore(sec,footer);else main.appendChild(sec)}
function navButton(){const b=document.createElement('button');b.className='navbtn';b.dataset.tab='diklatKsBcks';b.setAttribute('onclick',"showTab('diklatKsBcks')");b.innerHTML='<span class="ico">🎓</span>Diklat KS/BCKS';return b}
function ensureNav(){const nav=$('nav');if(!nav||nav.querySelector('[data-tab="diklatKsBcks"]'))return;if(!(isApplicant()||isReviewer()))return;const b=navButton();if(isReviewer()){const promotion=nav.querySelector('[data-tab="promotion"]');if(promotion)promotion.after(b);else nav.appendChild(b)}else{const services=nav.querySelector('[data-tab="services"]')||nav.querySelector('[data-tab="status"]');if(services)services.after(b);else nav.appendChild(b)}}
const stageIndex=s=>({ADMINISTRASI:0,SUBSTANSI:1,DIKLAT:2,SERTIFIKAT:3}[s]??0);
const stateLabel=(d,i)=>{if(i===0)return d?.admin_status||'BELUM';if(i===1)return d?.substansi_status||'TERKUNCI';if(i===2)return d?.diklat_status||'TERKUNCI';return d?.sertifikat_status||'TERKUNCI'};
function progressHtml(d){const cur=stageIndex(d?.workflow_stage||'ADMINISTRASI');const labels=['1. Seleksi Administrasi','2. Seleksi Substansi','3. Diklat','4. Penerbitan Sertifikat Diklat'];return `<div class="servicegrid" style="margin-bottom:14px">${labels.map((x,i)=>{const unlocked=i<=cur;const active=i===cur;return `<div class="service" style="border:${active?'2px solid #2563eb':'1px solid #dbe3ec'};opacity:${unlocked?1:.6}"><div class="small">LEVEL ${i+1}${active?' • AKTIF':''}</div><h3>${esc(x)}</h3><p>${esc(unlocked?stateLabel(d,i):'TERKUNCI')}</p></div>`}).join('')}</div>`}
async function myDetail(){const {data,error}=await sb.from('ks_bcks_submission_details').select('*').eq('user_id',profile().id).maybeSingle();if(error)throw error;return data}
async function filesFor(submissionId){if(!submissionId)return[];const {data,error}=await sb.from('submission_files').select('*').eq('submission_id',submissionId).order('created_at');if(error)throw error;return data||[]}
function applicantForm(d,files){const editable=!d||['DRAFT','DITOLAK'].includes(d.admin_status);const byCode=Object.fromEntries((files||[]).map(f=>[f.requirement_code,f]));return `<div class="card"><h3 style="margin-top:0">Level 1 • Seleksi Administrasi</h3><div class="grid"><label class="s6">Nama lengkap dan gelar<input id="ksbFullName" value="${esc(d?.full_name||profile().full_name||'')}" ${editable?'':'disabled'}></label><label class="s6">NIP<input id="ksbNip" value="${esc(d?.nip||profile().nip||'')}" ${editable?'':'disabled'}></label><label class="s6">Pangkat, Gol/Ruang<input id="ksbPangkat" value="${esc(d?.pangkat_golruang||'')}" placeholder="Contoh: Pembina, IV/a" ${editable?'':'disabled'}></label><label class="s6">Unit kerja<input id="ksbUnit" value="${esc(d?.unit_kerja||profile().unit||'')}" ${editable?'':'disabled'}></label><label class="s6">TMT penugasan KS<input id="ksbTmt" type="date" value="${esc(d?.tmt_penugasan_ks||'')}" ${editable?'':'disabled'}></label></div>${d?.admin_status==='DITOLAK'?`<div class="notice" style="margin-top:12px"><b>Perlu perbaikan:</b> ${esc(d.admin_note||'-')}</div>`:''}${editable?'<button class="btn" id="ksbSave" style="margin-top:12px">Simpan Data Administrasi</button>':''}</div><div class="card" style="margin-top:12px"><h3 style="margin-top:0">Upload Berkas <span class="small">(maksimal 500 KB per berkas; PDF/JPG/PNG)</span></h3><div class="servicegrid">${REQUIREMENTS.map(([code,label])=>{const f=byCode[code];return `<div class="service"><b>${esc(label)}</b><div class="small" style="margin:6px 0">${f?`✅ ${esc(f.file_name)} • ${Math.ceil(Number(f.file_size||0)/1024)} KB`:'Belum diunggah'}</div>${editable&&d?.submission_id?`<input type="file" data-ksb-upload="${code}" accept="application/pdf,image/jpeg,image/png">`:editable?'<div class="small">Simpan data administrasi terlebih dahulu.</div>':''}${f?`<button class="btn secondary" data-ksb-view="${esc(f.storage_path)}" style="margin-top:6px">Lihat berkas</button>`:''}</div>`}).join('')}</div>${editable&&d?.submission_id?'<button class="btn" id="ksbSubmit" style="margin-top:12px">Ajukan Seleksi Administrasi ke Dinas</button>':''}</div>`}
function applicantNextLevels(d){if(!d)return'';return `<div class="card" style="margin-top:12px"><h3 style="margin-top:0">Status Tahapan Berikutnya</h3><div class="servicegrid"><div class="service"><div class="small">LEVEL 2</div><h3>Seleksi Substansi</h3><p>${esc(d.workflow_stage==='ADMINISTRASI'?'Terkunci sampai Administrasi di-approve Dinas':d.substansi_status)}</p>${d.substansi_note?`<div class="small">Catatan: ${esc(d.substansi_note)}</div>`:''}</div><div class="service"><div class="small">LEVEL 3</div><h3>Diklat</h3><p>${esc(['ADMINISTRASI','SUBSTANSI'].includes(d.workflow_stage)?'Terkunci sampai lulus Seleksi Substansi':d.diklat_status)}</p>${d.diklat_note?`<div class="small">Catatan: ${esc(d.diklat_note)}</div>`:''}</div><div class="service"><div class="small">LEVEL 4</div><h3>Penerbitan Sertifikat Diklat</h3><p>${esc(d.workflow_stage!=='SERTIFIKAT'?'Terkunci sampai lulus Diklat':d.sertifikat_status)}</p>${d.sertifikat_status==='TERBIT'?`<div class="small">Nomor: ${esc(d.sertifikat_nomor)} • ${fmtDate(d.sertifikat_tanggal)}</div>`:''}</div></div></div>`}
async function renderApplicant(){const body=$('diklatKsBcksBody');if(!body)return;body.innerHTML='<div class="card"><div class="small">Memuat modul Diklat KS/BCKS…</div></div>';try{const d=await myDetail(),files=await filesFor(d?.submission_id);body.innerHTML=progressHtml(d)+applicantForm(d,files)+applicantNextLevels(d);bindApplicant(d,files)}catch(e){body.innerHTML=`<div class="card err">${esc(e.message||e)}</div>`}}
function formVals(){return {p_full_name:$('ksbFullName')?.value.trim(),p_nip:$('ksbNip')?.value.trim(),p_pangkat_golruang:$('ksbPangkat')?.value.trim(),p_unit_kerja:$('ksbUnit')?.value.trim(),p_tmt_penugasan_ks:$('ksbTmt')?.value||null}}
function bindApplicant(d,files){$('ksbSave')?.addEventListener('click',async()=>{try{const {data,error}=await sb.rpc('ks_bcks_save_administrasi',formVals());if(error)throw error;toast('Data administrasi tersimpan.');await renderApplicant()}catch(e){toast(e.message||String(e),true)}});document.querySelectorAll('[data-ksb-upload]').forEach(inp=>inp.addEventListener('change',async ev=>{const file=ev.target.files?.[0],code=ev.target.dataset.ksbUpload;if(!file)return;if(file.size>FILE_LIMIT)return toast('Berkas melebihi 500 KB.',true);if(!['application/pdf','image/jpeg','image/png'].includes(file.type))return toast('Format hanya PDF/JPG/PNG.',true);if(!d?.submission_id)return toast('Simpan data administrasi terlebih dahulu.',true);try{const old=(files||[]).find(x=>x.requirement_code===code);if(old){await sb.storage.from(BUCKET).remove([old.storage_path]);await sb.from('submission_files').delete().eq('id',old.id)}const clean=file.name.replace(/[^A-Za-z0-9._-]/g,'_');const path=`${profile().id}/${d.submission_id}/diklat-ks-bcks/${code}-${Date.now()}-${clean}`;const up=await sb.storage.from(BUCKET).upload(path,file,{upsert:false,contentType:file.type});if(up.error)throw up.error;const ins=await sb.from('submission_files').insert({submission_id:d.submission_id,user_id:profile().id,storage_path:path,file_name:file.name,file_size:file.size,mime_type:file.type,requirement_code:code});if(ins.error)throw ins.error;toast('Berkas berhasil diunggah.');await renderApplicant()}catch(e){toast(e.message||String(e),true)}}));document.querySelectorAll('[data-ksb-view]').forEach(b=>b.addEventListener('click',async()=>{const {data,error}=await sb.storage.from(BUCKET).createSignedUrl(b.dataset.ksbView,600);if(error)return toast(error.message,true);window.open(data.signedUrl,'_blank')}));$('ksbSubmit')?.addEventListener('click',async()=>{if(!confirm('Ajukan Seleksi Administrasi ke Dinas? Setelah diajukan, data tidak dapat diubah sampai ada hasil verifikasi.'))return;try{const {error}=await sb.rpc('ks_bcks_submit_administrasi',{p_submission_id:d.submission_id});if(error)throw error;toast('Seleksi Administrasi berhasil diajukan.');await renderApplicant()}catch(e){toast(e.message||String(e),true)}})}
async function reviewerData(){const {data,error}=await sb.from('ks_bcks_submission_details').select('*').order('updated_at',{ascending:false});if(error)throw error;return data||[]}
function reviewerActions(d){if(d.admin_status==='DIAJUKAN')return `<textarea id="note-${d.submission_id}" placeholder="Catatan verifikasi (opsional)"></textarea><div style="display:flex;gap:8px;margin-top:8px"><button class="btn" data-ksb-action="admin-ok" data-id="${d.submission_id}">Approve Administrasi</button><button class="btn secondary" data-ksb-action="admin-no" data-id="${d.submission_id}">Tolak/Perbaiki</button></div>`;if(d.workflow_stage==='SUBSTANSI')return `<textarea id="note-${d.submission_id}" placeholder="Catatan hasil Seleksi Substansi"></textarea><div style="display:flex;gap:8px;margin-top:8px"><button class="btn" data-ksb-action="sub-ok" data-id="${d.submission_id}">Lulus Substansi</button><button class="btn secondary" data-ksb-action="sub-no" data-id="${d.submission_id}">Tidak Lulus</button></div>`;if(d.workflow_stage==='DIKLAT')return `<textarea id="note-${d.submission_id}" placeholder="Catatan hasil Diklat"></textarea><div style="display:flex;gap:8px;margin-top:8px"><button class="btn" data-ksb-action="dik-ok" data-id="${d.submission_id}">Lulus Diklat</button><button class="btn secondary" data-ksb-action="dik-no" data-id="${d.submission_id}">Tidak Lulus</button></div>`;if(d.workflow_stage==='SERTIFIKAT'&&d.sertifikat_status!=='TERBIT')return `<div class="grid"><label class="s6">Nomor Sertifikat<input id="certno-${d.submission_id}"></label><label class="s6">Tanggal Sertifikat<input id="certdate-${d.submission_id}" type="date"></label></div><textarea id="note-${d.submission_id}" placeholder="Catatan sertifikat (opsional)"></textarea><button class="btn" data-ksb-action="cert" data-id="${d.submission_id}" style="margin-top:8px">Terbitkan Sertifikat</button>`;return `<div class="small">Tidak ada aksi pada status ini.</div>`}
async function renderReviewer(){const body=$('diklatKsBcksBody');if(!body)return;body.innerHTML='<div class="card"><div class="small">Memuat peserta Diklat KS/BCKS…</div></div>';try{const rows=await reviewerData();body.innerHTML=`<div class="card" style="margin-bottom:12px"><div class="info"><b>Workflow 4 level:</b> Administrasi → Substansi → Diklat → Penerbitan Sertifikat. Kenaikan level otomatis setelah hasil level sebelumnya dinyatakan lulus/disetujui.</div></div>${rows.length?rows.map(d=>`<div class="card" style="margin-bottom:12px"><div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap"><div><div class="small">${esc(d.nip)}</div><h3 style="margin:4px 0">${esc(d.full_name)}</h3><div>${esc(d.pangkat_golruang)} • ${esc(d.unit_kerja)}</div><div class="small">TMT KS: ${fmtDate(d.tmt_penugasan_ks)} • Update: ${fmtDateTime(d.updated_at)}</div></div><div><b>${esc(d.workflow_stage)}</b><div class="small">Adm ${esc(d.admin_status)} • Sub ${esc(d.substansi_status)} • Diklat ${esc(d.diklat_status)} • Sertifikat ${esc(d.sertifikat_status)}</div></div></div><div id="docs-${d.submission_id}" style="margin:12px 0"></div>${reviewerActions(d)}</div>`).join(''):'<div class="card"><div class="empty">Belum ada peserta.</div></div>'}`;for(const d of rows)await loadReviewerDocs(d.submission_id);bindReviewer()}catch(e){body.innerHTML=`<div class="card err">${esc(e.message||e)}</div>`}}
async function loadReviewerDocs(id){const box=$(`docs-${id}`);if(!box)return;const fs=await filesFor(id);const by=Object.fromEntries(fs.map(f=>[f.requirement_code,f]));box.innerHTML=`<div class="servicegrid">${REQUIREMENTS.map(([code,label])=>{const f=by[code];return `<div class="service"><b>${esc(label)}</b><div class="small">${f?'✅ '+esc(f.file_name):'❌ Belum ada'}</div>${f?`<button class="btn secondary" data-ksb-view="${esc(f.storage_path)}" style="margin-top:6px">Lihat</button>`:''}</div>`}).join('')}</div>`;box.querySelectorAll('[data-ksb-view]').forEach(b=>b.addEventListener('click',async()=>{const {data,error}=await sb.storage.from(BUCKET).createSignedUrl(b.dataset.ksbView,600);if(error)return toast(error.message,true);window.open(data.signedUrl,'_blank')}))}
function noteFor(id){return $(`note-${id}`)?.value?.trim()||null}
function bindReviewer(){document.querySelectorAll('[data-ksb-action]').forEach(b=>b.addEventListener('click',async()=>{const id=b.dataset.id,a=b.dataset.ksbAction;try{let res;if(a==='admin-ok'||a==='admin-no')res=await sb.rpc('ks_bcks_review_administrasi',{p_submission_id:id,p_approve:a==='admin-ok',p_note:noteFor(id)});else if(a==='sub-ok'||a==='sub-no')res=await sb.rpc('ks_bcks_set_substansi_result',{p_submission_id:id,p_lulus:a==='sub-ok',p_note:noteFor(id)});else if(a==='dik-ok'||a==='dik-no')res=await sb.rpc('ks_bcks_set_diklat_result',{p_submission_id:id,p_lulus:a==='dik-ok',p_note:noteFor(id)});else if(a==='cert')res=await sb.rpc('ks_bcks_issue_certificate',{p_submission_id:id,p_nomor:$(`certno-${id}`)?.value?.trim(),p_tanggal:$(`certdate-${id}`)?.value||null,p_note:noteFor(id)});if(res?.error)throw res.error;toast('Status berhasil diperbarui.');await renderReviewer()}catch(e){toast(e.message||String(e),true)}}))}
async function render(){ensureSection();ensureNav();if(isReviewer())return renderReviewer();if(isApplicant())return renderApplicant();$('diklatKsBcksBody').innerHTML='<div class="card"><div class="notice">Akun ini tidak memiliki akses ke modul Diklat KS/BCKS.</div></div>'}
ensureSection();ensureNav();const nav=$('nav');if(nav){let busy=false;new MutationObserver(()=>{if(busy)return;busy=true;queueMicrotask(()=>{ensureNav();busy=false})}).observe(nav,{childList:true})}
const priorShow=window.showTab;window.showTab=async id=>{ensureSection();ensureNav();await priorShow(id);if(id==='diklatKsBcks')await render()};
window.__simantabDiklatKsBcks={version:1,levels:['ADMINISTRASI','SUBSTANSI','DIKLAT','SERTIFIKAT'],fileLimit:FILE_LIMIT};
})();