/* SIMANTAB_DIKLAT_KS_BCKS_V2 */
/* SIMANTAB_DIKLAT_KS_BCKS_V3 */
(async()=>{
const wait=ms=>new Promise(r=>setTimeout(r,ms));
for(let i=0;i<200&&(!window.__simantabSb||!window.showTab||!window.__simantabProfile);i++)await wait(50);
const sb=window.__simantabSb,$=id=>document.getElementById(id),profile=()=>window.__simantabProfile||{};
if(!sb||!window.showTab)return;
const FILE_LIMIT=512000,BUCKET='simantab-documents';
const REQUIREMENTS=[
 ['IJAZAH_TERAKHIR','Ijazah terakhir'],['SERTIFIKAT_PENDIDIK','Sertifikat Pendidik'],['SK_PNS','SK PNS'],
 ['SKP_1','SKP 1'],['SKP_2','SKP 2'],['SK_PENGALAMAN_MANAJERIAL','SK pengalaman Manajerial'],
 ['SK_HUDIS','SK Hudis'],['SKCK','SKCK'],['PAKTA_INTEGRITAS','Pakta Integritas'],
 ['SURAT_PERNYATAAN_DIKLAT','Surat Pernyataan Bermeterai Bersedia Mengikuti Seluruh Proses Diklat KS']
];
const REVIEW_ROLES=new Set(['SUPER_ADMIN','KEPALA_DINAS','SEKRETARIS_DINAS','KABID','KASI_SD','KASI_SMP','SUBKOOR_TK']);
const isReviewer=()=>REVIEW_ROLES.has(profile().role)||String(profile().username||'').toLowerCase()==='kasim';
const isApplicant=()=>['GTK','KEPALA_SEKOLAH'].includes(profile().role);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtDate=v=>v?new Date(v).toLocaleDateString('id-ID'):'-';
const fmtDateTime=v=>v?new Date(v).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'}):'-';
const toast=(msg,bad=false)=>{let t=$('ksBcksToast');if(!t){t=document.createElement('div');t.id='ksBcksToast';Object.assign(t.style,{position:'fixed',right:'18px',bottom:'22px',zIndex:99999,maxWidth:'380px',padding:'12px 16px',borderRadius:'12px',boxShadow:'0 8px 28px #0003',fontWeight:'700'});document.body.appendChild(t)}t.style.background=bad?'#fee2e2':'#dcfce7';t.style.color=bad?'#991b1b':'#166534';t.textContent=msg;clearTimeout(t._x);t._x=setTimeout(()=>t.remove(),4000)};
function mainEl(){return document.querySelector('main.content')}
function ensureSection(){if($('diklatKsBcks'))return;const main=mainEl();if(!main)return;const sec=document.createElement('section');sec.id='diklatKsBcks';sec.className='section';sec.innerHTML='<div class="head"><div><h2>Diklat KS/BCKS</h2><p>Workflow seleksi administrasi, seleksi substansi, Diklat, dan pencatatan sertifikat dari pihak berwenang.</p></div></div><div id="diklatKsBcksBody"></div>';const footer=main.querySelector('.footer');if(footer)main.insertBefore(sec,footer);else main.appendChild(sec)}
function navButton(){const b=document.createElement('button');b.className='navbtn';b.dataset.tab='diklatKsBcks';b.setAttribute('onclick',"showTab('diklatKsBcks')");b.innerHTML='<span class="ico">🎓</span>Diklat KS/BCKS';return b}
function ensureNav(){const nav=$('nav');if(!nav||nav.querySelector('[data-tab="diklatKsBcks"]'))return;if(!(isApplicant()||isReviewer()))return;const b=navButton();if(isReviewer()){const p=nav.querySelector('[data-tab="promotion"]');p?p.after(b):nav.appendChild(b)}else{const s=nav.querySelector('[data-tab="services"]')||nav.querySelector('[data-tab="status"]');s?s.after(b):nav.appendChild(b)}}
const stageIndex=s=>({ADMINISTRASI:0,SUBSTANSI:1,DIKLAT:2,SERTIFIKAT:3}[s]??0);
const stateLabel=(d,i)=>i===0?(d?.admin_status||'BELUM'):i===1?(d?.substansi_status||'TERKUNCI'):i===2?(d?.diklat_status||'TERKUNCI'):(d?.sertifikat_status||'TERKUNCI');
function progressHtml(d){const cur=stageIndex(d?.workflow_stage||'ADMINISTRASI');const labels=['1. Seleksi Administrasi','2. Seleksi Substansi','3. Diklat','4. Pencatatan Sertifikat Diklat'];return `<div class="servicegrid" style="margin-bottom:14px">${labels.map((x,i)=>{const unlocked=i<=cur,active=i===cur;return `<div class="service" style="border:${active?'2px solid #2563eb':'1px solid #dbe3ec'};opacity:${unlocked?1:.6}"><div class="small">LEVEL ${i+1}${active?' • AKTIF':''}</div><h3>${esc(x)}</h3><p>${esc(unlocked?stateLabel(d,i):'TERKUNCI')}</p></div>`}).join('')}</div>`}
async function myDetail(){const {data,error}=await sb.from('ks_bcks_submission_details').select('*').eq('user_id',profile().id).maybeSingle();if(error)throw error;return data}
async function filesFor(id){if(!id)return[];const {data,error}=await sb.from('submission_files').select('*').eq('submission_id',id).order('created_at');if(error)throw error;return data||[]}
function applicantForm(d,files){const editable=!d||['DRAFT','DITOLAK'].includes(d.admin_status),by=Object.fromEntries((files||[]).map(f=>[f.requirement_code,f]));return `<div class="card"><h3 style="margin-top:0">Level 1 • Seleksi Administrasi</h3><div class="grid"><label class="s6">Nama lengkap dan gelar<input id="ksbFullName" value="${esc(d?.full_name||profile().full_name||'')}" ${editable?'':'disabled'}></label><label class="s6">NIP<input id="ksbNip" value="${esc(d?.nip||profile().nip||'')}" ${editable?'':'disabled'}></label><label class="s6">Pangkat, Gol/Ruang<input id="ksbPangkat" value="${esc(d?.pangkat_golruang||'')}" ${editable?'':'disabled'}></label><label class="s6">Unit kerja<input id="ksbUnit" value="${esc(d?.unit_kerja||profile().unit||'')}" ${editable?'':'disabled'}></label><label class="s6">TMT penugasan KS<input id="ksbTmt" type="date" value="${esc(d?.tmt_penugasan_ks||'')}" ${editable?'':'disabled'}></label></div>${d?.admin_status==='DITOLAK'?`<div class="notice" style="margin-top:12px"><b>Perlu perbaikan:</b> ${esc(d.admin_note||'-')}</div>`:''}${editable?'<button class="btn" id="ksbSave" style="margin-top:12px">Simpan Data Administrasi</button>':''}</div><div class="card" style="margin-top:12px"><h3 style="margin-top:0">Upload Berkas <span class="small">(maksimal 500 KB per berkas; PDF/JPG/PNG)</span></h3><div class="info" style="margin-bottom:12px"><b>Surat Pernyataan Bermeterai</b><br>Peserta wajib mengunggah surat pernyataan bersedia mengikuti seluruh proses Diklat KS yang telah ditandatangani dan dibubuhi meterai. <button class="btn secondary" id="ksbDownloadStatementTemplate" type="button" style="margin-top:8px">⬇ Unduh Template Surat Pernyataan (.doc)</button></div><div class="servicegrid">${REQUIREMENTS.map(([code,label])=>{const f=by[code];return `<div class="service"><b>${esc(label)}</b><div class="small" style="margin:6px 0">${f?`✅ ${esc(f.file_name)} • ${Math.ceil(Number(f.file_size||0)/1024)} KB`:'Belum diunggah'}</div>${editable&&d?.submission_id?`<input type="file" data-ksb-upload="${code}" accept="application/pdf,image/jpeg,image/png">`:editable?'<div class="small">Simpan data administrasi terlebih dahulu.</div>':''}${f?`<button class="btn secondary" data-ksb-view="${esc(f.storage_path)}" style="margin-top:6px">Lihat berkas</button>`:''}</div>`}).join('')}</div>${editable&&d?.submission_id?'<button class="btn" id="ksbSubmit" style="margin-top:12px">Ajukan Seleksi Administrasi ke Dinas</button>':''}</div>`}
function applicantNextLevels(d){if(!d)return'';return `<div class="card" style="margin-top:12px"><h3 style="margin-top:0">Status Tahapan Berikutnya</h3><div class="servicegrid"><div class="service"><div class="small">LEVEL 2</div><h3>Seleksi Substansi</h3><p>${esc(d.workflow_stage==='ADMINISTRASI'?'Terkunci sampai Administrasi di-approve Dinas':d.substansi_status)}</p>${d.substansi_note?`<div class="small">Catatan: ${esc(d.substansi_note)}</div>`:''}</div><div class="service"><div class="small">LEVEL 3</div><h3>Diklat</h3><p>${esc(['ADMINISTRASI','SUBSTANSI'].includes(d.workflow_stage)?'Terkunci sampai lulus Seleksi Substansi':d.diklat_status)}</p>${d.diklat_note?`<div class="small">Catatan: ${esc(d.diklat_note)}</div>`:''}</div><div class="service"><div class="small">LEVEL 4</div><h3>Pencatatan Sertifikat Diklat</h3><p>${esc(d.workflow_stage!=='SERTIFIKAT'?'Terkunci sampai lulus Diklat':d.sertifikat_status)}</p>${d.workflow_stage==='SERTIFIKAT'&&d.sertifikat_penerbit?`<div class="small">Penerbit: ${esc(d.sertifikat_penerbit)} • Nomor: ${esc(d.sertifikat_nomor||'-')} • ${fmtDate(d.sertifikat_tanggal)}</div>`:''}</div></div></div>`}
function certificateApplicantCard(d){
 if(!d||d.workflow_stage!=='SERTIFIKAT')return'';
 const editable=['MENUNGGU_PENCATATAN','DITOLAK'].includes(d.sertifikat_status);
 if(d.sertifikat_status==='TERCATAT')return `<div class="card" style="margin-top:12px"><h3 style="margin-top:0">Level 4 • Pencatatan Sertifikat Diklat</h3><div class="info"><b>DISETUJUI Admin KSPS</b><br>Data sertifikat dari pihak berwenang telah diverifikasi dan tercatat di SIMANTAB.</div><div class="small" style="margin-top:10px">Penerbit: ${esc(d.sertifikat_penerbit||'-')}<br>Nomor: ${esc(d.sertifikat_nomor||'-')}<br>Tanggal: ${fmtDate(d.sertifikat_tanggal)}</div></div>`;
 if(d.sertifikat_status==='DIAJUKAN')return `<div class="card" style="margin-top:12px"><h3 style="margin-top:0">Level 4 • Pencatatan Sertifikat Diklat</h3><div class="info"><b>Menunggu verifikasi Admin KSPS.</b><br>Data sertifikat telah diajukan dan sementara terkunci.</div><div class="small" style="margin-top:10px">Penerbit: ${esc(d.sertifikat_penerbit||'-')}<br>Nomor: ${esc(d.sertifikat_nomor||'-')}<br>Tanggal: ${fmtDate(d.sertifikat_tanggal)}</div></div>`;
 return `<div class="card" style="margin-top:12px"><h3 style="margin-top:0">Level 4 • Isi Data Sertifikat Diklat</h3><div class="notice" style="margin-bottom:12px">Data diisi oleh KS/peserta Diklat berdasarkan sertifikat yang diterbitkan pihak berwenang. Admin KSPS hanya memverifikasi dan menyetujui.</div>${d.sertifikat_status==='DITOLAK'?`<div class="notice" style="margin-bottom:12px"><b>Perlu perbaikan:</b> ${esc(d.sertifikat_note||'-')}</div>`:''}<div class="grid"><label class="s12">Lembaga/Pihak Penerbit<input id="ksbCertIssuer" value="${esc(d.sertifikat_penerbit||'')}" ${editable?'':'disabled'}></label><label class="s6">Nomor Sertifikat<input id="ksbCertNo" value="${esc(d.sertifikat_nomor||'')}" ${editable?'':'disabled'}></label><label class="s6">Tanggal Sertifikat<input id="ksbCertDate" type="date" value="${esc(d.sertifikat_tanggal||'')}" ${editable?'':'disabled'}></label></div><textarea id="ksbCertNote" placeholder="Catatan peserta (opsional)" ${editable?'':'disabled'}>${esc(d.sertifikat_status==='DITOLAK'?'':(d.sertifikat_note||''))}</textarea>${editable?'<button class="btn" id="ksbCertSubmit" style="margin-top:8px">Ajukan Data Sertifikat ke Admin KSPS</button>':''}</div>`;
}
async function renderApplicant(){const body=$('diklatKsBcksBody');if(!body)return;body.innerHTML='<div class="card"><div class="small">Memuat modul Diklat KS/BCKS…</div></div>';try{const d=await myDetail(),files=await filesFor(d?.submission_id);body.innerHTML=progressHtml(d)+applicantForm(d,files)+applicantNextLevels(d)+certificateApplicantCard(d);bindApplicant(d,files)}catch(e){body.innerHTML=`<div class="card err">${esc(e.message||e)}</div>`}}
function formVals(){return {p_full_name:$('ksbFullName')?.value.trim(),p_nip:$('ksbNip')?.value.trim(),p_pangkat_golruang:$('ksbPangkat')?.value.trim(),p_unit_kerja:$('ksbUnit')?.value.trim(),p_tmt_penugasan_ks:$('ksbTmt')?.value||null}}
function downloadStatementTemplate(d){
 const nama=$('ksbFullName')?.value?.trim()||d?.full_name||profile().full_name||'';
 const nip=$('ksbNip')?.value?.trim()||d?.nip||profile().nip||'';
 const pangkat=$('ksbPangkat')?.value?.trim()||d?.pangkat_golruang||'';
 const unit=$('ksbUnit')?.value?.trim()||d?.unit_kerja||profile().unit||'';
 const safe=v=>esc(v||'........................................................');
 const html=`<!doctype html><html><head><meta charset="utf-8"><title>Surat Pernyataan Diklat KS</title><style>@page{size:A4;margin:2.5cm}body{font-family:"Times New Roman",serif;font-size:12pt;line-height:1.5;color:#000}h1,h2{text-align:center;margin:0}h1{font-size:14pt;text-decoration:underline}h2{font-size:12pt;margin-bottom:24px}.tbl{border-collapse:collapse;width:100%;margin:12px 0 18px}.tbl td{padding:2px 4px;vertical-align:top}.n{width:34%}.c{width:3%}.sign{width:42%;margin-left:auto;text-align:center;margin-top:28px}.meterai{height:72px;display:flex;align-items:center;justify-content:center}.note{font-size:10pt;margin-top:20px}</style></head><body><h1>SURAT PERNYATAAN</h1><h2>BERSEDIA MENGIKUTI SELURUH PROSES DIKLAT KEPALA SEKOLAH</h2><p>Saya yang bertanda tangan di bawah ini:</p><table class="tbl"><tr><td class="n">Nama lengkap dan gelar</td><td class="c">:</td><td>${safe(nama)}</td></tr><tr><td>NIP</td><td>:</td><td>${safe(nip)}</td></tr><tr><td>Pangkat, Golongan/Ruang</td><td>:</td><td>${safe(pangkat)}</td></tr><tr><td>Jabatan</td><td>:</td><td>........................................................</td></tr><tr><td>Unit Kerja</td><td>:</td><td>${safe(unit)}</td></tr><tr><td>Alamat</td><td>:</td><td>........................................................</td></tr></table><p>Dengan ini menyatakan bahwa saya:</p><ol><li>Bersedia mengikuti seluruh tahapan dan proses Diklat Kepala Sekolah sesuai jadwal dan ketentuan penyelenggara.</li><li>Bersedia hadir, berpartisipasi aktif, menyelesaikan seluruh tugas, asesmen/evaluasi, dan kewajiban selama pelaksanaan Diklat Kepala Sekolah.</li><li>Bersedia mematuhi tata tertib serta ketentuan penyelenggaraan Diklat Kepala Sekolah.</li><li>Apabila tidak memenuhi kewajiban tanpa alasan yang dapat dipertanggungjawabkan, bersedia menerima tindak lanjut sesuai ketentuan yang berlaku.</li><li>Menyatakan bahwa surat ini dibuat dengan sebenar-benarnya, dalam keadaan sadar, dan tanpa paksaan dari pihak mana pun.</li></ol><p>Demikian surat pernyataan ini dibuat untuk dipergunakan sebagaimana mestinya.</p><div class="sign"><p>Batang, ................. 20....</p><p>Yang membuat pernyataan,</p><div class="meterai">Meterai Rp10.000</div><p><b><u>${safe(nama)}</u></b><br>NIP. ${safe(nip)}</p></div><div class="note"><b>Petunjuk:</b> cetak pada kertas A4, lengkapi bagian yang kosong, bubuhkan meterai dan tanda tangan, kemudian pindai menjadi PDF/JPG/PNG maksimal 500 KB untuk diunggah ke SIMANTAB.</div></body></html>`;
 const blob=new Blob(['\ufeff',html],{type:'application/msword;charset=utf-8'});
 const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Template_Surat_Pernyataan_Diklat_KS.doc';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);
}
function bindApplicant(d,files){
 $('ksbDownloadStatementTemplate')?.addEventListener('click',()=>downloadStatementTemplate(d));
 $('ksbSave')?.addEventListener('click',async()=>{try{const {error}=await sb.rpc('ks_bcks_save_administrasi',formVals());if(error)throw error;toast('Data administrasi tersimpan.');await renderApplicant()}catch(e){toast(e.message||String(e),true)}});
 document.querySelectorAll('[data-ksb-upload]').forEach(inp=>inp.addEventListener('change',async ev=>{const file=ev.target.files?.[0],code=ev.target.dataset.ksbUpload;if(!file)return;if(file.size>FILE_LIMIT)return toast('Berkas melebihi 500 KB.',true);if(!['application/pdf','image/jpeg','image/png'].includes(file.type))return toast('Format hanya PDF/JPG/PNG.',true);if(!d?.submission_id)return toast('Simpan data administrasi terlebih dahulu.',true);try{const old=(files||[]).find(x=>x.requirement_code===code);if(old){await sb.storage.from(BUCKET).remove([old.storage_path]);await sb.from('submission_files').delete().eq('id',old.id)}const clean=file.name.replace(/[^A-Za-z0-9._-]/g,'_'),path=`${profile().id}/${d.submission_id}/diklat-ks-bcks/${code}-${Date.now()}-${clean}`;const up=await sb.storage.from(BUCKET).upload(path,file,{upsert:false,contentType:file.type});if(up.error)throw up.error;const ins=await sb.from('submission_files').insert({submission_id:d.submission_id,user_id:profile().id,storage_path:path,file_name:file.name,file_size:file.size,mime_type:file.type,requirement_code:code});if(ins.error)throw ins.error;toast('Berkas berhasil diunggah.');await renderApplicant()}catch(e){toast(e.message||String(e),true)}}));
 document.querySelectorAll('[data-ksb-view]').forEach(b=>b.addEventListener('click',async()=>{const {data,error}=await sb.storage.from(BUCKET).createSignedUrl(b.dataset.ksbView,600);if(error)return toast(error.message,true);window.open(data.signedUrl,'_blank')}));
 $('ksbSubmit')?.addEventListener('click',async()=>{if(!confirm('Ajukan Seleksi Administrasi ke Dinas?'))return;try{const {error}=await sb.rpc('ks_bcks_submit_administrasi',{p_submission_id:d.submission_id});if(error)throw error;toast('Seleksi Administrasi berhasil diajukan.');await renderApplicant()}catch(e){toast(e.message||String(e),true)}});
 $('ksbCertSubmit')?.addEventListener('click',async()=>{if(!confirm('Ajukan data sertifikat ke Admin KSPS untuk diverifikasi?'))return;try{const {error}=await sb.rpc('ks_bcks_submit_certificate_data',{p_submission_id:d.submission_id,p_penerbit:$('ksbCertIssuer')?.value?.trim(),p_nomor:$('ksbCertNo')?.value?.trim(),p_tanggal:$('ksbCertDate')?.value||null,p_note:$('ksbCertNote')?.value?.trim()||null});if(error)throw error;toast('Data sertifikat berhasil diajukan ke Admin KSPS.');await renderApplicant()}catch(e){toast(e.message||String(e),true)}});
}
async function reviewerData(){const {data,error}=await sb.from('ks_bcks_submission_details').select('*').order('updated_at',{ascending:false});if(error)throw error;return data||[]}
function certSummary(d){return `<div class="info" style="margin-top:10px"><b>Data Sertifikat dari Peserta</b><br>Lembaga/Pihak Penerbit: ${esc(d.sertifikat_penerbit||'-')}<br>Nomor: ${esc(d.sertifikat_nomor||'-')}<br>Tanggal: ${fmtDate(d.sertifikat_tanggal)}${d.sertifikat_submitted_at?`<br>Diajukan: ${fmtDateTime(d.sertifikat_submitted_at)}`:''}</div>`}
function reviewerActions(d){
 if(d.admin_status==='DIAJUKAN')return `<textarea id="note-${d.submission_id}" placeholder="Catatan verifikasi (opsional)"></textarea><div style="display:flex;gap:8px;margin-top:8px"><button class="btn" data-ksb-action="admin-ok" data-id="${d.submission_id}">Approve Administrasi</button><button class="btn secondary" data-ksb-action="admin-no" data-id="${d.submission_id}">Tolak/Perbaiki</button></div>`;
 if(d.workflow_stage==='SUBSTANSI')return `<textarea id="note-${d.submission_id}" placeholder="Catatan hasil Seleksi Substansi"></textarea><div style="display:flex;gap:8px;margin-top:8px"><button class="btn" data-ksb-action="sub-ok" data-id="${d.submission_id}">Lulus Substansi</button><button class="btn secondary" data-ksb-action="sub-no" data-id="${d.submission_id}">Tidak Lulus</button></div>`;
 if(d.workflow_stage==='DIKLAT')return `<textarea id="note-${d.submission_id}" placeholder="Catatan hasil Diklat"></textarea><div style="display:flex;gap:8px;margin-top:8px"><button class="btn" data-ksb-action="dik-ok" data-id="${d.submission_id}">Lulus Diklat</button><button class="btn secondary" data-ksb-action="dik-no" data-id="${d.submission_id}">Tidak Lulus</button></div>`;
 if(d.workflow_stage==='SERTIFIKAT'&&d.sertifikat_status==='DIAJUKAN')return `${certSummary(d)}<textarea id="note-${d.submission_id}" placeholder="Catatan verifikasi Admin KSPS (opsional)"></textarea><div style="display:flex;gap:8px;margin-top:8px"><button class="btn" data-ksb-action="cert-ok" data-id="${d.submission_id}">Approve Data Sertifikat</button><button class="btn secondary" data-ksb-action="cert-no" data-id="${d.submission_id}">Tolak/Perbaiki</button></div>`;
 if(d.workflow_stage==='SERTIFIKAT'&&d.sertifikat_status==='TERCATAT')return `${certSummary(d)}<div class="small" style="margin-top:8px">✅ Sudah di-approve Admin KSPS.</div>`;
 if(d.workflow_stage==='SERTIFIKAT'&&d.sertifikat_status==='DITOLAK')return `${certSummary(d)}<div class="small" style="margin-top:8px">Menunggu peserta memperbaiki dan mengajukan ulang data sertifikat.</div>`;
 if(d.workflow_stage==='SERTIFIKAT')return `<div class="small">Menunggu KS/peserta Diklat mengisi dan mengajukan data sertifikat.</div>`;
 return `<div class="small">Tidak ada aksi pada status ini.</div>`;
}
async function renderReviewer(){const body=$('diklatKsBcksBody');if(!body)return;body.innerHTML='<div class="card"><div class="small">Memuat peserta Diklat KS/BCKS…</div></div>';try{const rows=await reviewerData();body.innerHTML=`<div class="card" style="margin-bottom:12px"><div class="info"><b>Workflow 4 level:</b> Administrasi → Substansi → Diklat → Pencatatan Sertifikat. Data sertifikat diisi peserta; Admin KSPS hanya memverifikasi/approve.</div></div>${rows.length?rows.map(d=>`<div class="card" style="margin-bottom:12px"><div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap"><div><div class="small">${esc(d.nip)}</div><h3 style="margin:4px 0">${esc(d.full_name)}</h3><div>${esc(d.pangkat_golruang)} • ${esc(d.unit_kerja)}</div><div class="small">TMT KS: ${fmtDate(d.tmt_penugasan_ks)} • Update: ${fmtDateTime(d.updated_at)}</div></div><div><b>${esc(d.workflow_stage)}</b><div class="small">Adm ${esc(d.admin_status)} • Sub ${esc(d.substansi_status)} • Diklat ${esc(d.diklat_status)} • Sertifikat ${esc(d.sertifikat_status)}</div></div></div><div id="docs-${d.submission_id}" style="margin:12px 0"></div>${reviewerActions(d)}</div>`).join(''):'<div class="card"><div class="empty">Belum ada peserta.</div></div>'}`;for(const d of rows)await loadReviewerDocs(d.submission_id);bindReviewer()}catch(e){body.innerHTML=`<div class="card err">${esc(e.message||e)}</div>`}}
async function loadReviewerDocs(id){const box=$(`docs-${id}`);if(!box)return;const fs=await filesFor(id),by=Object.fromEntries(fs.map(f=>[f.requirement_code,f]));box.innerHTML=`<div class="servicegrid">${REQUIREMENTS.map(([code,label])=>{const f=by[code];return `<div class="service"><b>${esc(label)}</b><div class="small">${f?'✅ '+esc(f.file_name):'❌ Belum ada'}</div>${f?`<button class="btn secondary" data-ksb-view="${esc(f.storage_path)}" style="margin-top:6px">Lihat</button>`:''}</div>`}).join('')}</div>`;box.querySelectorAll('[data-ksb-view]').forEach(b=>b.addEventListener('click',async()=>{const {data,error}=await sb.storage.from(BUCKET).createSignedUrl(b.dataset.ksbView,600);if(error)return toast(error.message,true);window.open(data.signedUrl,'_blank')}))}
const noteFor=id=>$(`note-${id}`)?.value?.trim()||null;
function bindReviewer(){document.querySelectorAll('[data-ksb-action]').forEach(b=>b.addEventListener('click',async()=>{const id=b.dataset.id,a=b.dataset.ksbAction;try{let res;if(a==='admin-ok'||a==='admin-no')res=await sb.rpc('ks_bcks_review_administrasi',{p_submission_id:id,p_approve:a==='admin-ok',p_note:noteFor(id)});else if(a==='sub-ok'||a==='sub-no')res=await sb.rpc('ks_bcks_set_substansi_result',{p_submission_id:id,p_lulus:a==='sub-ok',p_note:noteFor(id)});else if(a==='dik-ok'||a==='dik-no')res=await sb.rpc('ks_bcks_set_diklat_result',{p_submission_id:id,p_lulus:a==='dik-ok',p_note:noteFor(id)});else if(a==='cert-ok'||a==='cert-no')res=await sb.rpc('ks_bcks_review_certificate',{p_submission_id:id,p_approve:a==='cert-ok',p_note:noteFor(id)});if(res?.error)throw res.error;toast('Status berhasil diperbarui.');await renderReviewer()}catch(e){toast(e.message||String(e),true)}}))}
async function render(){ensureSection();ensureNav();if(isReviewer())return renderReviewer();if(isApplicant())return renderApplicant();$('diklatKsBcksBody').innerHTML='<div class="card"><div class="notice">Akun ini tidak memiliki akses ke modul Diklat KS/BCKS.</div></div>'}
ensureSection();ensureNav();const nav=$('nav');if(nav){let busy=false;new MutationObserver(()=>{if(busy)return;busy=true;queueMicrotask(()=>{ensureNav();busy=false})}).observe(nav,{childList:true})}
const priorShow=window.showTab;window.showTab=async id=>{ensureSection();ensureNav();await priorShow(id);if(id==='diklatKsBcks')await render()};
window.__simantabDiklatKsBcks={version:3,levels:['ADMINISTRASI','SUBSTANSI','DIKLAT','SERTIFIKAT'],certificateFlow:'PESERTA_ISI_ADMIN_KSPS_APPROVE',fileLimit:FILE_LIMIT};
})();